name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole converter.py

    - name: Copy FFmpeg
      run: |
        cp ffmpeg.exe dist/

    - name: Upload executable and FFmpeg
      uses: actions/upload-artifact@v4
      with:
        name: converter-exe
        path: |
          dist/converter.exe
          dist/ffmpeg.exe
